name: Build and Deploy Ionic App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Ionic App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Hosting Service
        run: |
          # Add commands to deploy your app (e.g., to GitHub Pages, Firebase Hosting, etc.)
          # Make sure to set up any necessary environment variables or secrets.
